### ISSUE TITLE
Does it supports video playback ?

### ISSUE THREAD

**Issue by footballs** [leixiaohua1020/ffplaymfc#2]
Respected developer,
It can't play video file. But plays audio file very great.
Do you have any suggestion for adding video playback ?

waiting for response

**Comment by baifengjiu** [comment]
> Respected developer,
> It can't play video file. But plays audio file very great.
> Do you have any suggestion for adding video playback ?
> 
> waiting for response

The developer died in July 2016. It's sad that he can't answer your question any more. This is his blog and may help you.
https://blog.csdn.net/leixiaohua1020

**Comment by footballs** [comment]
Oh no ! I read his blogs and codes,
He was so well experienced one,
I am very sad to hear that.
